### ISSUE TITLE
Using ansible_ssh_port for determining default rules is unreliable

### ISSUE THREAD

**Issue by danielkza** [arillso/ansible.shorewall#8]
`ansible_ssh_port` doesn't always represent the port SSH is *listening to* in a host if it is being accessed behind some form of proxying. For example, when testing out the role in a Docker container, the Shorewall config was generated with the port exposed in my host (a high port) instead of 22, breaking SSH in the process.

The port included in the default config should probably be moved to a variable (maybe `shorewall_default_ssh_port`), so if anyone really wants to use `ansible_ssh_port` they can set it to that.

**Comment by sbaerlocher** [comment]
I implemented it and is now available in version `v1.0.9`.
